
-- auto exported game_attributes 
-- including native attributes and custom attributes 


---@enum UGCNativeGameAttributeType
UGCNativeGameAttributeType = { 
	--Character [血量-Health],
	Character_Health = 'Health',
	--Character [最大血量-HealthMax],
	Character_HealthMax = 'HealthMax',
	--Character [技能急速-SkillCDRecoverRate],
	Character_SkillCDRecoverRate = 'SkillCDRecoverRate',
	--Character [信号值-SignalHP],
	Character_SignalHP = 'SignalHP',
	--Character [最大信号值-SignalHPMax],
	Character_SignalHPMax = 'SignalHPMax',
	--Character [呼吸值-Breath],
	Character_Breath = 'Breath',
	--Character [额外速度值-AdditiveSpeedValueWrapper],
	Character_AdditiveSpeedValueWrapper = 'AdditiveSpeedValueWrapper',
	--Character [当前能量值-EnergyCurrent],
	Character_EnergyCurrent = 'Energy|EnergyCurrent',
	--Character [UGC移动速度倍率-UGCGeneralMoveSpeedScale],
	Character_UGCGeneralMoveSpeedScale = 'UGCGeneralMoveSpeedScale',

---------------------------------------------------------

	--Weapon [射击前处理（拉栓）时长-PreFireTime],
	Weapon_PreFireTime = 'ShootWeaponEntityComp|PreFireTime',
	--Weapon [射击后处理时长-PostFireTime],
	Weapon_PostFireTime = 'ShootWeaponEntityComp|PostFireTime',
	--Weapon [单发换弹开始动作加第一发子弹时长-ReloadDurationStart],
	Weapon_ReloadDurationStart = 'ShootWeaponEntityComp|ReloadDurationStart',
	--Weapon [单发换弹循环加一发子弹时长-ReloadDurationLoop],
	Weapon_ReloadDurationLoop = 'ShootWeaponEntityComp|ReloadDurationLoop',
	--Weapon [全弹夹换弹时长-ReloadTime],
	Weapon_ReloadTime = 'ShootWeaponEntityComp|ReloadTime',
	--Weapon [全弹夹换弹时间修改参数-ReloadTimeModifier],
	Weapon_ReloadTimeModifier = 'ShootWeaponEntityComp|ReloadTimeModifier',
	--Weapon [战术换弹时长-ReloadTimeTactical],
	Weapon_ReloadTimeTactical = 'ShootWeaponEntityComp|ReloadTimeTactical',
	--Weapon [战术换弹时间修改参数-ReloadTimeTacticalModifier],
	Weapon_ReloadTimeTacticalModifier = 'ShootWeaponEntityComp|ReloadTimeTacticalModifier',
	--Weapon [单发战术换弹时间修改参数-ReloadTimeTacticalOneByOneModifier],
	Weapon_ReloadTimeTacticalOneByOneModifier = 'ShootWeaponEntityComp|ReloadTimeTacticalOneByOneModifier',
	--Weapon [所有换弹时间修改参数-AllReloadTimeModifier],
	Weapon_AllReloadTimeModifier = 'ShootWeaponEntityComp|AllReloadTimeModifier',
	--Weapon [全弹夹换弹开始到拔出弹夹时间-ReloadTimeMagOut],
	Weapon_ReloadTimeMagOut = 'ShootWeaponEntityComp|ReloadTimeMagOut',
	--Weapon [战术换弹开始到拔出弹夹时间-ReloadTimeMagOutTactical],
	Weapon_ReloadTimeMagOutTactical = 'ShootWeaponEntityComp|ReloadTimeMagOutTactical',
	--Weapon [全弹夹换弹时弹夹插入到换弹结束的时间-ReloadTimeMagIn],
	Weapon_ReloadTimeMagIn = 'ShootWeaponEntityComp|ReloadTimeMagIn',
	--Weapon [战术换弹时弹夹插入到换弹结束的时间-ReloadTimeMagInTactical],
	Weapon_ReloadTimeMagInTactical = 'ShootWeaponEntityComp|ReloadTimeMagInTactical',
	--Weapon [垂直后坐力修改参数-VerticalRecoilFactorModifier],
	Weapon_VerticalRecoilFactorModifier = 'ShootWeaponEntityComp|VerticalRecoilFactorModifier',
	--Weapon [水平后坐力修改参数-HorizontalRecoilFactorModifier],
	Weapon_HorizontalRecoilFactorModifier = 'ShootWeaponEntityComp|HorizontalRecoilFactorModifier',
	--Weapon [后坐回正参数-AccessoriesRecoveryFactor],
	Weapon_AccessoriesRecoveryFactor = 'ShootWeaponEntityComp|AccessoriesRecoveryFactor',
	--Weapon [散弹枪垂直散布-ShotGunVerticalSpread],
	Weapon_ShotGunVerticalSpread = 'ShootWeaponEntityComp|ShotGunVerticalSpread',
	--Weapon [散弹枪水平散布-ShotGunHorizontalSpread],
	Weapon_ShotGunHorizontalSpread = 'ShootWeaponEntityComp|ShotGunHorizontalSpread',
	--Weapon [所有散布因子-GameDeviationFactor],
	Weapon_GameDeviationFactor = 'ShootWeaponEntityComp|GameDeviationFactor',
	--Weapon [最终散布修改参数-DeviationFactorModifier],
	Weapon_DeviationFactorModifier = 'ShootWeaponEntityComp|DeviationFactorModifier',
	--Weapon [枪械开镜速度-WeaponAimInTime],
	Weapon_WeaponAimInTime = 'ShootWeaponEntityComp|WeaponAimInTime',
	--Weapon [倍镜类别-SightType],
	Weapon_SightType = 'ShootWeaponEntityComp|SightType',
	--Weapon [开镜开火后坐力动画表现系数-RecoilKickADS],
	Weapon_RecoilKickADS = 'ShootWeaponEntityComp|RecoilKickADS',
	--Weapon [开火抖动幅度-AnimationKick],
	Weapon_AnimationKick = 'ShootWeaponEntityComp|AnimationKick',
	--Weapon [UGC换弹时间影响因子-ReloadTimeFactorWrapper],
	Weapon_ReloadTimeFactorWrapper = 'ReloadTimeFactorWrapper',
	--Weapon [UGC切枪时间影响因子-SwitchTimeFactorWrapper],
	Weapon_SwitchTimeFactorWrapper = 'SwitchTimeFactorWrapper',
	--Weapon [UGC攻击间隔影响因子-ShootIntervalFactorWrapper],
	Weapon_ShootIntervalFactorWrapper = 'ShootIntervalFactorWrapper',
	--Weapon [UGC后坐力影响因子-RecoilFactorWrapper],
	Weapon_RecoilFactorWrapper = 'RecoilFactorWrapper',
	--Weapon [UGC散布影响因子-DeviationFactorWrapper],
	Weapon_DeviationFactorWrapper = 'DeviationFactorWrapper',
	--Weapon [UGC子弹基础伤害-BaseImpactDamageWrapper],
	Weapon_BaseImpactDamageWrapper = 'BaseImpactDamageWrapper',
	--Weapon [UGC子弹最低伤害-MinimumImpactDamageWrapper],
	Weapon_MinimumImpactDamageWrapper = 'MinimumImpactDamageWrapper',
	--Weapon [UGC子弹飞行速度-BulletFireSpeedWrapper],
	Weapon_BulletFireSpeedWrapper = 'BulletFireSpeedWrapper',
	--Weapon [UGC最大射程-BulletRangeWrapper],
	Weapon_BulletRangeWrapper = 'BulletRangeWrapper',
	--Weapon [UGC一次拉栓子弹装填数量-MaxBulletNumInBarrelWrapper],
	Weapon_MaxBulletNumInBarrelWrapper = 'MaxBulletNumInBarrelWrapper',
	--Weapon [UGC弹匣容量-MaxBulletNumInOneClipWrapper],
	Weapon_MaxBulletNumInOneClipWrapper = 'MaxBulletNumInOneClipWrapper',
	--Weapon [UGC全自动射击间隔-AutoShootIntervalWrapper],
	Weapon_AutoShootIntervalWrapper = 'AutoShootIntervalWrapper',
	--Weapon [UGC连发射击间隔-BurstShootCDWrapper],
	Weapon_BurstShootCDWrapper = 'BurstShootCDWrapper',
	--Weapon [UGC连发数量-BurstShootBulletsNumWrapper],
	Weapon_BurstShootBulletsNumWrapper = 'BurstShootBulletsNumWrapper',
	--Weapon [UGC连发子弹间隔-BurstShootIntervalWrapper],
	Weapon_BurstShootIntervalWrapper = 'BurstShootIntervalWrapper',
}; 

UGCNativeGameAttributeTypeCommentMap = { 

---------------------------------------------------------

	['Health'] = 'Character [血量-Health]', 
	['HealthMax'] = 'Character [最大血量-HealthMax]', 
	['SkillCDRecoverRate'] = 'Character [技能急速-SkillCDRecoverRate]', 
	['SignalHP'] = 'Character [信号值-SignalHP]', 
	['SignalHPMax'] = 'Character [最大信号值-SignalHPMax]', 
	['Breath'] = 'Character [呼吸值-Breath]', 
	['AdditiveSpeedValueWrapper'] = 'Character [额外速度值-AdditiveSpeedValueWrapper]', 
	['Energy|EnergyCurrent'] = 'Character [当前能量值-EnergyCurrent]', 
	['UGCGeneralMoveSpeedScale'] = 'Character [UGC移动速度倍率-UGCGeneralMoveSpeedScale]', 

---------------------------------------------------------

	['ShootWeaponEntityComp|PreFireTime'] = 'Weapon [射击前处理（拉栓）时长-PreFireTime]', 
	['ShootWeaponEntityComp|PostFireTime'] = 'Weapon [射击后处理时长-PostFireTime]', 
	['ShootWeaponEntityComp|ReloadDurationStart'] = 'Weapon [单发换弹开始动作加第一发子弹时长-ReloadDurationStart]', 
	['ShootWeaponEntityComp|ReloadDurationLoop'] = 'Weapon [单发换弹循环加一发子弹时长-ReloadDurationLoop]', 
	['ShootWeaponEntityComp|ReloadTime'] = 'Weapon [全弹夹换弹时长-ReloadTime]', 
	['ShootWeaponEntityComp|ReloadTimeModifier'] = 'Weapon [全弹夹换弹时间修改参数-ReloadTimeModifier]', 
	['ShootWeaponEntityComp|ReloadTimeTactical'] = 'Weapon [战术换弹时长-ReloadTimeTactical]', 
	['ShootWeaponEntityComp|ReloadTimeTacticalModifier'] = 'Weapon [战术换弹时间修改参数-ReloadTimeTacticalModifier]', 
	['ShootWeaponEntityComp|ReloadTimeTacticalOneByOneModifier'] = 'Weapon [单发战术换弹时间修改参数-ReloadTimeTacticalOneByOneModifier]', 
	['ShootWeaponEntityComp|AllReloadTimeModifier'] = 'Weapon [所有换弹时间修改参数-AllReloadTimeModifier]', 
	['ShootWeaponEntityComp|ReloadTimeMagOut'] = 'Weapon [全弹夹换弹开始到拔出弹夹时间-ReloadTimeMagOut]', 
	['ShootWeaponEntityComp|ReloadTimeMagOutTactical'] = 'Weapon [战术换弹开始到拔出弹夹时间-ReloadTimeMagOutTactical]', 
	['ShootWeaponEntityComp|ReloadTimeMagIn'] = 'Weapon [全弹夹换弹时弹夹插入到换弹结束的时间-ReloadTimeMagIn]', 
	['ShootWeaponEntityComp|ReloadTimeMagInTactical'] = 'Weapon [战术换弹时弹夹插入到换弹结束的时间-ReloadTimeMagInTactical]', 
	['ShootWeaponEntityComp|VerticalRecoilFactorModifier'] = 'Weapon [垂直后坐力修改参数-VerticalRecoilFactorModifier]', 
	['ShootWeaponEntityComp|HorizontalRecoilFactorModifier'] = 'Weapon [水平后坐力修改参数-HorizontalRecoilFactorModifier]', 
	['ShootWeaponEntityComp|AccessoriesRecoveryFactor'] = 'Weapon [后坐回正参数-AccessoriesRecoveryFactor]', 
	['ShootWeaponEntityComp|ShotGunVerticalSpread'] = 'Weapon [散弹枪垂直散布-ShotGunVerticalSpread]', 
	['ShootWeaponEntityComp|ShotGunHorizontalSpread'] = 'Weapon [散弹枪水平散布-ShotGunHorizontalSpread]', 
	['ShootWeaponEntityComp|GameDeviationFactor'] = 'Weapon [所有散布因子-GameDeviationFactor]', 
	['ShootWeaponEntityComp|DeviationFactorModifier'] = 'Weapon [最终散布修改参数-DeviationFactorModifier]', 
	['ShootWeaponEntityComp|WeaponAimInTime'] = 'Weapon [枪械开镜速度-WeaponAimInTime]', 
	['ShootWeaponEntityComp|SightType'] = 'Weapon [倍镜类别-SightType]', 
	['ShootWeaponEntityComp|RecoilKickADS'] = 'Weapon [开镜开火后坐力动画表现系数-RecoilKickADS]', 
	['ShootWeaponEntityComp|AnimationKick'] = 'Weapon [开火抖动幅度-AnimationKick]', 
	['ReloadTimeFactorWrapper'] = 'Weapon [UGC换弹时间影响因子-ReloadTimeFactorWrapper]', 
	['SwitchTimeFactorWrapper'] = 'Weapon [UGC切枪时间影响因子-SwitchTimeFactorWrapper]', 
	['ShootIntervalFactorWrapper'] = 'Weapon [UGC攻击间隔影响因子-ShootIntervalFactorWrapper]', 
	['RecoilFactorWrapper'] = 'Weapon [UGC后坐力影响因子-RecoilFactorWrapper]', 
	['DeviationFactorWrapper'] = 'Weapon [UGC散布影响因子-DeviationFactorWrapper]', 
	['BaseImpactDamageWrapper'] = 'Weapon [UGC子弹基础伤害-BaseImpactDamageWrapper]', 
	['MinimumImpactDamageWrapper'] = 'Weapon [UGC子弹最低伤害-MinimumImpactDamageWrapper]', 
	['BulletFireSpeedWrapper'] = 'Weapon [UGC子弹飞行速度-BulletFireSpeedWrapper]', 
	['BulletRangeWrapper'] = 'Weapon [UGC最大射程-BulletRangeWrapper]', 
	['MaxBulletNumInBarrelWrapper'] = 'Weapon [UGC一次拉栓子弹装填数量-MaxBulletNumInBarrelWrapper]', 
	['MaxBulletNumInOneClipWrapper'] = 'Weapon [UGC弹匣容量-MaxBulletNumInOneClipWrapper]', 
	['AutoShootIntervalWrapper'] = 'Weapon [UGC全自动射击间隔-AutoShootIntervalWrapper]', 
	['BurstShootCDWrapper'] = 'Weapon [UGC连发射击间隔-BurstShootCDWrapper]', 
	['BurstShootBulletsNumWrapper'] = 'Weapon [UGC连发数量-BurstShootBulletsNumWrapper]', 
	['BurstShootIntervalWrapper'] = 'Weapon [UGC连发子弹间隔-BurstShootIntervalWrapper]', 
}; 

---@enum UGCCustomGameAttributeType
UGCCustomGameAttributeType = { 
}; 

UGCCustomGameAttributeTypeCommentMap = { 
}; 

